name: example action

on:
  pull_request:
    branches:
      - main

jobs:
  example-action:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1.1.1
        with:
          github-token: ${{ github.token }}
          number: ${{ github.event.number }}
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
                github-token: ${{ github.token}}
                number: ${{ github.event.number }}
                method: squash
